import Colors from './color';
import {
  back_light,
  settings_light,
  right_arrow_light,
  disabled_switch_light,
  enabled_switch_light,
  play_light,
  pause_light,
  bottom_left_light,
  bottom_right_light,
  checkbox_selected_light,
  checkbox_unselected_light,
  radiobutton_selected_light,
  radiobutton_unselected_light,
  session_finish_light,
  info_light,
  badge_1_light,
  badge_2_light,
  badge_3_light,
  badge_4_light,
  close_light,
} from '../images';
import { ThemeType } from './themes';

export const DARK = 'dark';
export const LIGHT = 'light';

export const ThemesVersionGreen: ThemeType = {
    light: {
      name: LIGHT,
      colors: {
        screen_background: Colors.theme_color_6,
        element_background: Colors.white_shade_0,
        primary_text_color: Colors.dark_grey,
        secondary_text_color: Colors.dark_grey,
        settings_text_color: Colors.dark_grey,
        header_text_color: Colors.dark_grey,
        settings_button_color: Colors.black,
        audio_player_background: Colors.white_shade_0,
        forward_backward_background: Colors.white_shade_0,
        forward_backward_bordercolor: Colors.black,
        audio_player_text_color: Colors.dark_grey_2,
        progress_bar_color: Colors.black,
        uncompleted_bar_color: Colors.grey_shade_2,
        all_white_color: Colors.dark_grey_2,
        text_field_place_holder: Colors.green_shade_6,
        field_background_color: Colors.white_shade_0,
        button_background: Colors.black,
        button_text: Colors.white_shade_0,
        range_bar: Colors.black,
        gesundheit_link_color: Colors.white_shade_0,
        modal_text: Colors.black,
        pager_background: Colors.white_shade_0,
        pager_border: Colors.bar_gray,
        pager_dot_active: Colors.black,
        pager_dot_inactive: Colors.grey_shade_2,
      },
      icons: {
        back: back_light,
        settings: settings_light,
        right_arrow: right_arrow_light,
        disabled_switch: disabled_switch_light,
        enabled_switch: enabled_switch_light,
        play_button: play_light,
        pause_button: pause_light,
        bottom_bar_left: bottom_left_light,
        bottom_bar_right: bottom_right_light,
        checkbox_selected: checkbox_selected_light,
        checkbox_unselected: checkbox_unselected_light,
        radiobutton_selected: radiobutton_selected_light,
        radiobutton_unselected: radiobutton_unselected_light,
        session_finish: session_finish_light,
        info: info_light,
        badges: [badge_1_light, badge_2_light, badge_3_light, badge_4_light],
        close: close_light,
      },
    },
    dark: {
      name: DARK,
      colors: {
        screen_background: Colors.theme_color_6,
        element_background: Colors.white_shade_0,
        primary_text_color: Colors.dark_grey,
        secondary_text_color: Colors.dark_grey,
        settings_text_color: Colors.dark_grey,
        header_text_color: Colors.dark_grey,
        settings_button_color: Colors.black,
        audio_player_background: Colors.white_shade_0,
        forward_backward_background: Colors.white_shade_0,
        forward_backward_bordercolor: Colors.black,
        audio_player_text_color: Colors.dark_grey_2,
        progress_bar_color: Colors.black,
        uncompleted_bar_color: Colors.grey_shade_2,
        all_white_color: Colors.dark_grey_2,
        text_field_place_holder: Colors.green_shade_6,
        field_background_color: Colors.white_shade_0,
        button_background: Colors.black,
        button_text: Colors.white_shade_0,
        range_bar: Colors.black,
        gesundheit_link_color: Colors.white_shade_0,
        modal_text: Colors.black,
        pager_background: Colors.white_shade_0,
        pager_border: Colors.bar_gray,
        pager_dot_active: Colors.black,
        pager_dot_inactive: Colors.grey_shade_2,
      },
      icons: {
        back: back_light,
        settings: settings_light,
        right_arrow: right_arrow_light,
        disabled_switch: disabled_switch_light,
        enabled_switch: enabled_switch_light,
        play_button: play_light,
        pause_button: pause_light,
        bottom_bar_left: bottom_left_light,
        bottom_bar_right: bottom_right_light,
        checkbox_selected: checkbox_selected_light,
        checkbox_unselected: checkbox_unselected_light,
        radiobutton_selected: radiobutton_selected_light,
        radiobutton_unselected: radiobutton_unselected_light,
        session_finish: session_finish_light,
        info: info_light,
        badges: [badge_1_light, badge_2_light, badge_3_light, badge_4_light],
        close: close_light,
      },
    },
  };
  