
name: CI/CD Pipline
on: 
  push: 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "21.x"
      - name: Install server dependencies     
        run: yarn install
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "21.x"
      - name: Run Unit Test
        run: yarn test