
name: CI/CD Pipline
on: 
  push: 
  pull_request:
jobs:
  build-lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"
      - name: Install all dependencies     
        run: yarn install
      - name: Run Unit Test
        run: yarn test  
      