
name: CI/CD Pipline
on: 
  push: 
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "21.x"
      - name: Install server dependencies     
        run: yarn install