name: CI/CD Pipline For Staging
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Build
        uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - name: Install all dependencies
        run: yarn install
      - name: Run lint process
        run: yarn lint
      - name: Run format process
        run: yarn format
      - name: Run all Unit Test
        run: yarn test
      - name: Run E2E Cypress
        uses: cypress-io/github-action@v6
        with:
          build: yarn run build
          start: yarn run start
          wait-on: http://localhost:3000
      - name: Build for Staging
        run: |
          unset CI
          yarn build
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'build'
